import { createEvents, EventAttributes, DateArray } from 'ics';

// Event type from extraction API
export interface ExtractedEvent {
  event_name: string;
  category: 'exam' | 'assignment' | 'project' | 'quiz';
  date: string; // ISO format YYYY-MM-DD
  time?: string; // HH:MM format (24-hour)
  is_all_day: boolean;
  context: string;
  raw_text: string;
  confidence?: number;
}

// Color mapping for calendar clients
const CATEGORY_COLORS: Record<string, string> = {
  exam: 'RED',
  assignment: 'BLUE',
  project: 'GREEN',
  quiz: 'YELLOW',
};

// Convert ISO date string and time to ICS date array format
function parseDateTime(isoDate: string, time?: string): DateArray {
  const date = new Date(isoDate);
  const year = date.getFullYear();
  const month = date.getMonth() + 1; // ICS months are 1-indexed
  const day = date.getDate();

  if (time) {
    // Parse time string (HH:MM format)
    const [hours, minutes] = time.split(':').map(Number);
    return [year, month, day, hours, minutes];
  }

  // All-day event (no time component)
  return [year, month, day];
}

// Generate alarm/reminder for event
function createAlarm(category: string): EventAttributes['alarms'] {
  if (category === 'exam') {
    // Exam: 1 day before
    return [
      {
        action: 'display',
        description: 'Exam tomorrow!',
        trigger: { hours: 24, before: true },
      },
    ];
  }

  if (category === 'assignment' || category === 'project') {
    // Assignment/Project: 2 days before
    return [
      {
        action: 'display',
        description: 'Assignment due in 2 days',
        trigger: { hours: 48, before: true },
      },
    ];
  }

  if (category === 'quiz') {
    // Quiz: 1 day before
    return [
      {
        action: 'display',
        description: 'Quiz tomorrow!',
        trigger: { hours: 24, before: true },
      },
    ];
  }

  return undefined;
}

// Generate a single ICS event from extracted event
function convertToICSEvent(
  event: ExtractedEvent,
  courseCode: string = 'COURSE'
): EventAttributes {
  const start = parseDateTime(event.date, event.time);

  // For all-day events, we don't need an end date
  // For timed events, default to 1 hour duration
  let end: DateArray | undefined = undefined;
  if (!event.is_all_day && event.time) {
    const date = new Date(event.date);
    const [hours, minutes] = event.time.split(':').map(Number);
    date.setHours(hours + 1); // Add 1 hour
    end = [
      date.getFullYear(),
      date.getMonth() + 1,
      date.getDate(),
      date.getHours(),
      minutes,
    ];
  }

  // Build event title with emoji prefix
  const categoryEmoji = {
    exam: '🔴',
    assignment: '🔵',
    project: '🟢',
    quiz: '🟡',
  }[event.category] || '';

  const title = `${categoryEmoji} [${courseCode}] ${event.event_name}`;

  // Build description with context
  const description = [
    event.context,
    '',
    `Category: ${event.category.toUpperCase()}`,
    `Original text: "${event.raw_text}"`,
    event.confidence ? `Confidence: ${event.confidence}` : '',
    '',
    'Generated by Academic Command Center',
  ]
    .filter(Boolean)
    .join('\n');

  const icsEvent: EventAttributes = {
    start,
    end,
    title,
    description,
    categories: [event.category.toUpperCase()],
    status: 'CONFIRMED',
    busyStatus: event.category === 'exam' ? 'BUSY' : 'FREE',
    alarms: createAlarm(event.category),
  };

  return icsEvent;
}

// Generate .ics file content from array of events
export function generateICS(
  events: ExtractedEvent[],
  options: {
    courseCode?: string;
    courseName?: string;
    calendarName?: string;
  } = {}
): { success: boolean; data?: string; error?: string } {
  const { courseCode = 'COURSE', courseName, calendarName } = options;

  try {
    // Convert all events to ICS format
    const icsEvents = events.map((event) =>
      convertToICSEvent(event, courseCode)
    );

    // Generate ICS file
    const { error, value } = createEvents(icsEvents);

    if (error) {
      return {
        success: false,
        error: `Failed to generate ICS file: ${error.message}`,
      };
    }

    if (!value) {
      return {
        success: false,
        error: 'No ICS content generated',
      };
    }

    // Add calendar name to ICS content if provided
    let icsContent = value;
    if (calendarName) {
      icsContent = icsContent.replace(
        'BEGIN:VCALENDAR',
        `BEGIN:VCALENDAR\nX-WR-CALNAME:${calendarName}\nNAME:${calendarName}`
      );
    }

    return {
      success: true,
      data: icsContent,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message || 'Unknown error generating ICS file',
    };
  }
}

// Helper to generate filename for download
export function generateFilename(options: {
  courseCode?: string;
  courseName?: string;
}): string {
  const { courseCode, courseName } = options;

  if (courseName) {
    return `${courseName.replace(/\s+/g, '_')}.ics`;
  }

  if (courseCode) {
    return `${courseCode}_calendar.ics`;
  }

  return `syllabus_calendar_${Date.now()}.ics`;
}

// Statistics helper
export function getEventStats(events: ExtractedEvent[]): {
  total: number;
  byCategory: Record<string, number>;
  dateRange: { start: string; end: string } | null;
} {
  const byCategory: Record<string, number> = {
    exam: 0,
    assignment: 0,
    project: 0,
    quiz: 0,
  };

  let minDate: Date | null = null;
  let maxDate: Date | null = null;

  events.forEach((event) => {
    byCategory[event.category]++;

    const date = new Date(event.date);
    if (!minDate || date < minDate) minDate = date;
    if (!maxDate || date > maxDate) maxDate = date;
  });

  return {
    total: events.length,
    byCategory,
    dateRange:
      minDate && maxDate
        ? {
            start: minDate.toISOString().split('T')[0],
            end: maxDate.toISOString().split('T')[0],
          }
        : null,
  };
}
